# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7817749e0cfc190c094164d58a5b3e7351a07fdab0e2a49db0b22c87e1d086215ea53111f20ad9fe73786c5949e52e59f3866b8c66803f7aeb89c545e5a77729

test:
  secret_key_base: 431c8fbe18f4f1aca18801c215d1daf3237f1a03187eb2e66ffa9cafbbf50aad47fe3bec4869af32ceda50ede18777a07123a674d8251a4e4497d61e87c23272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
